model:
  name: transformer_kws
  layers: 12
  heads: 1
  mlp_dim: 256
  num_output_classes: 4
  embedding_dim: 64
  norm_type: postnorm

data:
  time_window: 101
  frequency: 128
  patch_size_t: 5
  patch_size_f: 16

training:
  batch: 32
  lr: 3e-4
  save_dir_tr: ./outputs/trainer
  save_dir_wandb: ./outputs/wandb
  model_path: ./outputs/models
  epochs: 20

dataset:
  sample_rate: 16000
  destination: ./kws_transformer/dataset

mfcc_settings:
  sample_rate: 16000
  n_mfcc: 128
  n_mels: 128
  n_fft: 480
  hop_length: 160