program: kws_transformer/train.py

project: kws-transformer
name: background-8
description: Check how large a dataset is required

method: grid

metric:
  name: val_loss
  goal: minimize

parameters:
  data.dataset_size:
    values: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}